os: osx
osx_image: xcode10.2
sudo: required
addons:
  homebrew:
    taps: zhaofeng-shu33/liblemonformula
install:
  - sudo python3 -m pip install info_cluster sklearn networkx six ete3
script:
# used for testing
  - curl https://raw.githubusercontent.com/zhaofeng-shu33/info-clustering-python-binding/master/graph_cut_py_test.py -o test.py
  - python3 -c "from info_cluster import psp;print(psp.__version__)"
  - python3 -c "from info_cluster import InfoCluster"
  - python3 test.py
  - brew uninstall python
  - brew install zhaofeng-shu33/liblemonformula/python
  - sudo python3 -m pip install info_cluster sklearn networkx six ete3  
  - python3 -c "from info_cluster import psp;print(psp.__version__)"
  - python3 -c "from info_cluster import InfoCluster"
  - python3 test.py
