os: osx
sudo: required
addons:
  homebrew:
    packages:
      - python
install:
  - sudo python3 -m pip install info_cluster
  - python3.7 -m pip install info_cluster
script:
# used for testing
  - curl https://raw.githubusercontent.com/zhaofeng-shu33/info-clustering-python-binding/master/graph_cut_py_test.py -o test.py
  - python3 -c "from info_cluster import psp;print(psp.__version__)"
  - python3 -c "from info_cluster import InfoCluster"
  - python3 run graph_cut_py_test.py
  - python3.7 -c "from info_cluster import psp;print(psp.__version__)"
  - python3.7 -c "from info_cluster import InfoCluster"
  - python3.7 run graph_cut_py_test.py
  