version: 1.0.{build}
install:
- cmd: >-
    C:\Python37-x64\python.exe -m pip install info_cluster

    C:\Python36-x64\python.exe -m pip install info_cluster

    curl https://raw.githubusercontent.com/zhaofeng-shu33/info-clustering-python-binding/master/graph_cut_py_test.py -o test.py
build: off
test_script:
- cmd: >-
    C:\Python37-x64\python.exe -c "import pspartition; print(pspartition.__version__)"

    C:\Python37-x64\python.exe test.py

    C:\Python36-x64\python.exe -c "import pspartition; print(pspartition.__version__)"

    C:\Python36-x64\python.exe test.py