version: 1.0.{build}
install:
- cmd: >-
    C:\Python37-x64\python.exe -m pip install info_cluster scikit-learn six ete3 networkx

    C:\Python36-x64\python.exe -m pip install info_cluster scikit-learn six ete3 networkx

    curl https://raw.githubusercontent.com/zhaofeng-shu33/info-clustering-python-binding/master/graph_cut_py_test.py -o test.py
build: off
test_script:
- cmd: >-
    C:\Python37-x64\python.exe -c "from info_cluster import psp; print(psp.__version__)"

    C:\Python37-x64\python.exe test.py

    C:\Python36-x64\python.exe -c "from info_cluster import psp; print(psp.__version__)"

    C:\Python36-x64\python.exe test.py