version: 2
jobs:
  build-py36:
    docker:
      - image: circleci/python:3.6.8
    steps:
      - run: 
          name: install test
          command: |
            curl https://raw.githubusercontent.com/zhaofeng-shu33/info-clustering-python-binding/master/graph_cut_py_test.py -o test.py
            python -m pip install --user info_cluster six ete3 sklearn numpy networkx
            python --version
            python -c "from info_cluster import psp;print(psp.__version__)"
            python -c "from info_cluster import InfoCluster"
            python test.py          
  build-py37:
    docker:
      - image: circleci/python:3.7.3
    steps:
      - run: 
          name: install test
          command: |
            curl https://raw.githubusercontent.com/zhaofeng-shu33/info-clustering-python-binding/master/graph_cut_py_test.py -o test.py
            python -m pip install --user info_cluster six ete3 sklearn numpy networkx
            python --version
            python -c "from info_cluster import psp;print(psp.__version__)"
            python -c "from info_cluster import InfoCluster"
            python test.py            
