version: 2
jobs:
  build-py36:
    docker:
      - image: circleci/python:3.6.8
    steps:
      - run: 
          name: install test
          command: |
            curl https://raw.githubusercontent.com/zhaofeng-shu33/info-clustering-python-binding/master/info_cluster/test_info_cluster.py -o test.py
            python -m pip install --user info_cluster six ete3 sklearn numpy networkx
            python --version
            python -c "import pspartition; print(pspartition.__version__)"
            python -c "from info_cluster import InfoCluster"
            python test.py          
  build-py37:
    docker:
      - image: circleci/python:3.7.3
    steps:
      - run: 
          name: install test
          command: |
            curl https://raw.githubusercontent.com/zhaofeng-shu33/info-clustering-python-binding/master/info_cluster/test_info_cluster.py -o test.py
            python -m pip install --user info_cluster
            python --version
            python -c "import pspartition; print(pspartition.__version__)"
            python -c "from info_cluster import InfoCluster"
            python test.py            
workflows:
  version: 2
  build_and_test:
    jobs:
      - build-py36
      - build-py37